### ISSUE TITLE
Bounty remove check (1)

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#3]
# Problem

status-go handles each RPC request differently according a few params:
 - method
 - configuration of remote node (Upstream.Enabled/Disabled)

Routing logic is in `geth/rpc/router.go`. List of the methods that should be router to remote or local have been changed and updated, and there seems to be no clear vision if that list is complete and/or correct.

This causes bugs that hard to detect with current tests. (PR https://github.com/status-im/status-go/pull/377 as an example of solving such type of bugs).

# Implementation

 - review current list of methods in router and update it if needed
 - define clear rules of how this list is composed, which are the rules for this list
 - put it into wiki or other easily-discoverable docs platform (comments?)

# Acceptance Criteria

 - there is a documentation on the methods routing list
 - list is updated if needed after review

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 40.00 ANT: 400000000000.00
Contract address: [0xa145c72651464557065f45be1a0713ac194bfd9b](https://ropsten.etherscan.io/address/0xa145c72651464557065f45be1a0713ac194bfd9b)
![QR Code](https://openbounty.status.im:444/qr/NewOrGanizationSOB/RepoSOB1_2/bounty/3/51a72fe35cf980c36fe08f9453fd7b672a1db7b07a9f7f1a8a3ec19b4af725a4/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.

**Comment by churik** [comment]
no claim was added

**Comment by Chu127001** [comment]
no claim
